# Generated by Django 5.1.5 on 2025-02-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MIDIFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='FileName')),
                ('content', models.FileField(upload_to='midi_files/', verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CreationTime')),
            ],
            options={
                'verbose_name': 'MIDIファイル',
                'verbose_name_plural': 'MIDIファイル',
            },
        ),
    ]
